mario = Cook.create(name:"Mario Mario",username: "mario123", password:"iluvpeach", email:"mario@pasta.com")
luigi = Cook.create(name:"Luigi Mario", username: "luigi456", password: "yoshi", email: "luigi@pasta.com")
italian = Cuisine.create(name:"Italian")
pasta = Recipe.create(name:"pasta latte", cuisine: italian)
pasta.cook = mario
italian = Cuisine.create(name:"Italian")
eggplant_parm = Recipe.create(name:"eggplant parmesan",cook: luigi)
eggplant_parm.cuisine = italian
american = Cuisine.create(name:"American")
bob = Cook.create(name:"Bob",username:"bobsburgers",password:"lynne",email:"bob@burgers.com")
burger = Recipe.create(name:"A Leek Of Their Own Burger", cook:bob, cuisine: american)
